### PR TITLE
Improve atlas details within atlas API docs

### LINKED ISSUE #247: Add more details for new atlases
There are some atlases missing on [this page](https://brainglobe.info/documentation/brainglobe-atlasapi/usage/atlas-details.html), including:
- barrel cortex atlas
- axotlotl atlas

### PR DESCRIPTION
**Pull request by adamltyson**
Closes #247

### CODE REVIEW

**Review by IgorTatarnikov — APPROVED** [review]
:+1: Looks good! Do we merge this with the change to `build_shphinx_docs` action or wait for the resolution of that discussion?

**Comment by adamltyson** [comment]
I think the fix on our side is simple, and I just pushed. This should be safe even with a new release of the build workflow.

**Comment by IgorTatarnikov** [comment]
Should [`1877475` (#249)](https://github.com/brainglobe/brainglobe.github.io/pull/249/commits/1877475a63312cad9e33294588b850d50a05b2d6) be reverted before merging?

**Comment by adamltyson** [comment]
I don't think so. I think it's better to make sure we're using the latest release (well 2.x), rather than whatever is on main.

**Pull request merged**
