### PR TITLE
update segmentation screenshots

### LINKED ISSUE #125: Update segmentation screenshots in line with changes in #124
Screenshots currently still show "load atlas" dropdown menu, which was removed in #124

### PR DESCRIPTION
**Pull request by alessandrofelder**
## Description

**What is this PR**

- [x] Bug fix
- [ ] Addition of a new feature
- [ ] Other

**Why is this PR needed?**

Segmentation screenshot tutorial screenshots need updating after #124 .

**What does this PR do?**

Updates these screenshots accordingly.

## References

Closes #125 

## How has this PR been tested?

Visual inspection of 1D and 3D segmentation tutorials in local build.

## Is this a breaking change?

No.

## Does this PR require an update to the documentation?

No

## Checklist:

- [x] The code has been tested locally
- [n/a] Tests have been added to cover all new functionality (unit & integration)
- [n/a] The documentation has been updated to reflect any changes
- [x] The code has been formatted with [pre-commit](https://pre-commit.com/)

### CODE REVIEW

**Comment by alessandrofelder** [comment]
Not sure why screenshots have doubled in size, but suggest it's not worth investigating further at this point, as ratio has stayed the same?

**Comment by adamltyson** [comment]
> Not sure why screenshots have doubled in size, but suggest it's not worth investigating further at this point, as ratio has stayed the same?

Different monitor?

**Review by adamltyson — APPROVED** [review]
Looks good. I've replaced the image that's in the `documentation` section too. I'll let you merge once you've taken a look at that.

**Comment by alessandrofelder** [comment]
> Different monitor?

Nope - same monitor. I suspect different version of some qt-related dependency causing the `screenshot_maker` code to ignore my attempt at forcing the window size 🤷 

> I've replaced the image that's in the documentation section too. I'll let you merge once you've taken a look at that.

Awesome, thank you 🙏

**Pull request merged**
