### PR TITLE
TensorFlow to PyTorch migration

### LINKED ISSUE #183: [Feature] Update cellfinder/brainmapper documentation to account for keras 3.0, torch migration
**Describe the solution you'd like**
We need to update the documentation to account for `cellfinder` migrating to a `torch` backend. In theory, any mention of `tensorflow` should be examined and translated to a relevant `torch` equivalent.

**Describe alternatives you've considered**
None

### PR DESCRIPTION
**Pull request by IgorTatarnikov**
Before submitting a pull request (PR), please read the [contributing guide](https://github.com/brainglobe/.github/blob/main/CONTRIBUTING.md).

Please fill out as much of this template as you can, but if you have any problems or questions, just leave a comment and we will help out :)

## Description

**What is this PR**

- [ ] Bug fix
- [ ] Addition of a new feature
- [x] Other

**Why is this PR needed?**
We're changing the backend for `cellfinder` to use PyTorch instead of Tensorflow.

**What does this PR do?**
Removes most mentions of TensorFlow as it relates to `cellfinder` and replaces them with the relevant PyTorch instruction.

I've made these changes with the understanding that `cellfinder` is the only package that currently uses TensorFlow so migrating to PyTorch allows us to not instruct users on setting it up. I didn't change the mentions in [error-messages.md](https://github.com/brainglobe/brainglobe.github.io/blob/main/docs/source/documentation/cellfinder/troubleshooting/error-messages.md) as those remain relevant for people using the older version.

## References
Closes #183 

## How has this PR been tested?
Built locally.

## Is this a breaking change?
No.

## Checklist:

- [x] The code has been tested locally
- [x] The code has been formatted with [pre-commit](https://pre-commit.com/)

### CODE REVIEW

**Comment by IgorTatarnikov** [comment]
I had one question about these [lines](https://github.com/brainglobe/brainglobe.github.io/blob/cbb4f1035a377c9e97ad4f9fe96525e938619cda/docs/source/community/developers/index.md?plain=1#L51C1-L53C35), after we remove TensorFlow are we still going to recommend a Python 3.10 dev environment? If so, what's our official reason?

@adamltyson @alessandrofelder

**Comment by adamltyson** [comment]
Nope, once we move to torch, the [plan is to update everything to recommend 3.11](https://github.com/brainglobe/brainglobe.github.io/issues/108). Once all dependencies also support it, we can then move to 3.12. 

tensorflow is/was the only thing keeping us on 3.10

**Comment by adamltyson** [comment]
Yeah we haven't updated supported versions while we've been stuck with 3.10 as the latest. I suggest once the torch version of cf is released, we go through and NEP29-ify everything.

**Review by alessandrofelder — APPROVED** [review]
Looks good to me - we should wait until https://github.com/brainglobe/cellfinder/pull/418#issue-comment-box is merged before merging this.

**Comment by adamltyson** [comment]
> Looks good to me - we should wait until https://github.com/brainglobe/cellfinder/pull/418#issue-comment-box is merged before merging this.

*is released.

**Comment by adamltyson** [comment]
I've re-run the build. I've sometimes noticed that biorxiv does this, but it works itself out

**Pull request merged**
