### PR TITLE
Update dependency tree in light of widget refactoring.

### PR DESCRIPTION
**Pull request by willGraham01**
Since `brainrender-napari` now fetches it's widgets from `brainglobe-utils`, we need to update the dependency tree to reflect this.

Staging this PR until a new version of the metapackage with all necessary new versions released and updated is ready. @K-Meech

### CODE REVIEW

**Comment by adamltyson** [comment]
A new version of the metapackage has now been released. There's been some movement of code (e.g. from cellfinder -> brainglobe-utils), but I think the new dependency tree is still valid.

**Comment by alessandrofelder** [comment]
I think it's missing the dependency of `brainrender-napari` on `brainglobe-utils`, introduced [here](https://github.com/brainglobe/brainrender-napari/pull/139/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711).

**Comment by alessandrofelder** [comment]
...in other words, I think this could/should be merged... but looks like we're replacing a light-mode image with a dark-mode image?

**Comment by alessandrofelder** [comment]
@willGraham01 could you have another look at this and ask for my review?

**Comment by willGraham01** [comment]
Should be in light mode now - I think this was opened with the changes in https://github.com/brainglobe/brainglobe-meta/pull/49/ in mind, so if no other package dependencies have been moved around, things should be OK.

**Review by alessandrofelder — APPROVED** [review]

**Pull request merged**
